export type Patient = {id:string;name:string;age:number;medication:string;dose:string;scenario:string;refills:number[];symptom:number;steps:number;missing:boolean;conflict:boolean;alternative:boolean;department:string};
export type Review = {id:string;patientId:string;date:string;status:string;note:string;actions:string[];confidence:number};
const names=['Arjun Mehta','Priya Nair','Daniel Chen','Sofia Martinez','Aisha Khan','James Wilson','Ananya Rao','Oliver Brooks','Mei Tan','Rohan Kapoor','Isabella Rossi','Amir Hassan','Emma Clarke','Vikram Singh','Grace Kim','Noah Taylor','Sara Ahmed','Lucas Martin','Kavya Patel','Ethan Lee'];
const scenarios=['Persistent pattern','Stable','Intermittent pattern','One-off irregularity','Conflicting signals','Missing data','Prescription change','Possible access issue'];
export const patients:Patient[]=names.map((name,i)=>{const s=i%8;return {id:`DT-${[1042,1087,1132,1148,1156,1173,1184,1191,1204,1217,1228,1235,1246,1253,1268,1274,1286,1293,1301,1314][i]}`,name,age:39+(i*7)%35,medication:['Metformin','Amlodipine','Atorvastatin','Levothyroxine'][i%4],dose:['500 mg','5 mg','20 mg','50 mcg'][i%4],scenario:scenarios[s],refills:s===1?[30,29,30,30]:s===3?[30,30,30,33]:s===2?[35,30,38,36]:[30,34,38,38+s%3],symptom:s===1?2:s===3?2.2:s===4?1.9:4,steps:s===1?7500:s===3?7300:s===4?7800:6100,missing:s===5,conflict:s===4,alternative:s===6||s===7,department:i%2?'Primary care':'Internal medicine'};});
export function evidence(p:Patient){return [{label:'Refill deviation',value:Math.min(24,Math.max(0,p.refills.at(-1)!-30)*3)},{label:'Repeated pattern',value:p.refills.filter(v=>v>32).length>=2?18:0},{label:'Symptom change',value:p.symptom>3?15:0},{label:'Activity change',value:p.steps<6500?12:0},{label:'Signal agreement',value:p.symptom>3&&p.steps<6500?8:0},{label:'Missing data',value:p.missing?-20:0},{label:'Conflicting signals',value:p.conflict?-15:0},{label:'Alternative explanation',value:p.alternative?-18:0}];}
export const confidence=(p:Patient)=>Math.max(8,Math.min(97,10+evidence(p).reduce((a,e)=>a+e.value,0)));
export const needsReview=(p:Patient,t:number,r:Review[])=>confidence(p)>=t&&!r.some(r=>r.patientId===p.id);
export const status=(p:Patient,t:number,r:Review[])=>r.find(r=>r.patientId===p.id)?.status||(confidence(p)>=t?(confidence(p)>=85?'High priority':'Needs review'):confidence(p)>20?'Monitor':'Stable');
export function events(p:Patient){return [{type:'Prescription',date:'2026-06-03',title:'Prescription established',detail:`${p.medication} ${p.dose}; expected refill every 30 days.`},{type:'Pharmacy',date:'2026-07-05',title:'Medication collected',detail:`Observed refill interval: ${p.refills[1]} days.`},{type:'Symptoms',date:'2026-08-25',title:'Symptom observation',detail:`${p.symptom}/10 compared with baseline 2.1/10.`},{type:'Pharmacy',date:'2026-09-04',title:'Refill cycle assessed',detail:`Current observed cycle: ${p.refills.at(-1)} days, compared with a 30-day baseline.`},{type:'Wearable',date:'2026-09-14',title:p.missing?'Wearable data incomplete':'Activity observation',detail:p.missing?'Four days missing; evidence quality reduced.':`${p.steps.toLocaleString()} steps/day versus baseline 7,400.`},{type:'Follow-up',date:'2026-09-16',title:'Follow-up recorded',detail:`${p.scenario}. Review context with patient before drawing conclusions.`}];}
